name: payfast
description: A Flutter package for PayFast payment integration.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.5 <4.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^5.0.0
  test: ^1.16.0

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this package as a Flutter package.
  uses-material-design: true